urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import logout
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
admin.autodiscover()
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

from tastypie.api import Api
from common.api import ImageResource, UserResource, CountryResource, \
StateResource, CityResource, CategoryResource, ProductResource, TimingResource, ContactResource, UserProfileResource, \
LocationResource, EntityRatingCategoryMapResource, RatingCategoryResource, RatingVoteResource, CommentResource, ActivityResource
from mall.api import FloorPlanResource, MallResource, MallImageResource, MallNearbyResource, \
MallFloorPlanResource, FloorPlanResource, MallContactResource, MallTimingResource
from store.api import StoreResource, MallStoreResource, StoreImageResource, StoreTimingResource, \
StoreProductResource, StoreOfferResource, EventTypeResource, EventResource, SearchResource
from brand.api import BrandResource, BrandProductResource, BrandStoreResource, BrandImageResource

v1_api = Api(api_name = 'v1')

v1_api.register(MallImageResource())
v1_api.register(MallNearbyResource())
v1_api.register(MallFloorPlanResource())
v1_api.register(FloorPlanResource())
v1_api.register(MallContactResource())
v1_api.register(MallTimingResource())
v1_api.register(ImageResource())
v1_api.register(UserResource())
v1_api.register(MallResource())
v1_api.register(ProductResource())
v1_api.register(CountryResource())
v1_api.register(StateResource())
v1_api.register(CityResource())
v1_api.register(CategoryResource())
v1_api.register(StoreResource())
v1_api.register(MallStoreResource())
v1_api.register(StoreImageResource())
v1_api.register(StoreTimingResource())
v1_api.register(UserProfileResource())
v1_api.register(StoreProductResource())
v1_api.register(StoreOfferResource())
v1_api.register(EventTypeResource())
v1_api.register(TimingResource())
v1_api.register(BrandResource())
v1_api.register(BrandStoreResource())
v1_api.register(BrandProductResource())
v1_api.register(EventResource())
v1_api.register(ContactResource())
v1_api.register(SearchResource())
v1_api.register(LocationResource())
v1_api.register(RatingCategoryResource())
v1_api.register(EntityRatingCategoryMapResource())
v1_api.register(RatingVoteResource())
v1_api.register(CommentResource())
v1_api.register(ActivityResource())
v1_api.register(BrandImageResource())

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'malta.views.home', name='home'),
    # url(r'^malta/', include('malta.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(v1_api.urls)),
    # url(r'^main/', 'mall.views.main', name = "home"),
    # url(r'^malls/', 'mall.views.get_malls_summary', name = "mall_list"),
    # url(r'^stores/', 'store.views.get_stores_summary', name = "store_list"),
    # url(r'^create/(?P<entity_type>[mall,store]{4,5})', 'common.views.create', name = "create"),
    # (r'^accounts/', include('allauth.urls')),
    # (r'^search/', include('haystack.urls')),
    # url(r'^post_comment/', 'common.views.post_comment', name = "post_comment"),
     (r'^admin/', include(admin.site.urls)),
     url(r'^login/', 'django.contrib.auth.views.login', {'template_name': 'login.html' }),
     (r'^logout/', logout, {'next_page': '/main/'}),
    # url(r'^post-login/', 'common.views.post_login', name = 'post-login'),
    # url(r'^signup/', 'common.views.sign_up', name = 'signup'),
    # url(r'^vote/(?P<map_id>[0-9]+)/(?P<ctype_id>[0-9]+)/(?P<obj_id>[0-9]+)/(?P<rating>[0-9]+)/$', 'common.views.put_rating', name = 'vote' ),
    # url(r'^store/(?P<id>[0-9]+)/(?P<slug>[-_\w]+)/$', 'store.views.store_view', name = 'store_view'),
    # url(r'^mall/(?P<id>[0-9]+)/(?P<slug>[-_\w]+)/$', 'mall.views.mall_view', name = 'mall_view'),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
) + staticfiles_urlpatterns()

common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from datetime import datetime
from django.contrib.contenttypes.generic import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from log import get_request_logger
logger = get_request_logger()
from django import forms
from django.conf import settings
from django.core.management import call_command
from django.db.models.signals import post_save
from geoposition.fields import GeopositionField
import os
from tastypie.models import create_api_key
from django.contrib.auth.models import User
import uuid, urllib
import utils, strings
# Create your models here.



models.signals.post_save.connect(create_api_key, sender=User)

class User_profile(models.Model):
    USER_ROLES = (
            ('ru', 'Regular User'),
            ('mm', 'Mall Manager'),
            ('sm', 'Store Manager'),
            ('sa', 'Site Admin'),
        )
    user = models.ForeignKey( User, null = True )
    firstname = models.CharField( max_length = 50 )
    lastname = models.CharField( max_length = 50  )
    role = models.CharField( max_length = 2, choices = USER_ROLES )
    email = models.EmailField( unique = True )
    is_verified = models.BooleanField( default = False )

    def is_profile_complete( self ):
        logger.debug('( self.firstname %s self.lastname %s self.role %s self.email ) %s' \
         %(( self.firstname, self.lastname, self.role, self.email )))
        return ( self.firstname and self.lastname and self.role and self.email )

    def is_role_valid( self, role ):
        return ( role in [ user_role[0] for user_role in USER_ROLES ] )
    def __unicode__(self):
        return unicode(self.user) + ' profile'
    
    def get_user_options(self, user):
        options = {'My Profile': reverse('common.views')}
        if self.role == 'ru':
            return 

    def save( self, *args, **kwargs):
        if self.id and self.email != User_profile.objects.get(id = self.id ).email:
            send_email( self )
        super(User_profile, self).save(*args, **kwargs)


class Profile_verification(models.Model):
    guid = models.CharField( max_length = 100 )
    profile = models.ForeignKey( User_profile )

class Image(models.Model):
    image = models.ImageField( upload_to = 'images', null = True )
    name  = models.CharField( max_length = 100, null = True, blank = True )
    description = models.TextField( null = True, blank = True )
    
    def __unicode__(self):
        return self.name if self.name else "Image Not Named"

    def save(self, *args, **kwargs):
        if not self.name and self.image:
            self.name = os.path.basename ( self.image.file.name )
        elif not self.name:
            self.name = "Image Not Named"
        super( Image, self ).save( *args, **kwargs )

    def delete(self, *args, **kwargs):
        try:
            if self.image:
                os.remove( self.image.file.name )
        except Exception,e:
            logger.exception('exception deleting file: %s' %(e))

        super( Image, self ).delete(*args, **kwargs)

    def get_image_url(self):
        return self.image.url
    

class Category(models.Model):

    CATEGORY_TYPES = (
                    ('EVE', 'Event'),
                    ('OFF', 'Offer'),
                    ('SHO', 'Shop'),
                    ('BRD', 'Brand'),
        )

    name = models.CharField(max_length = 50)
    description = models.TextField( null = True, blank = True)
    category_type = models.CharField( max_length = 3, choices = CATEGORY_TYPES )

    def __unicode__(self):
        return unicode(self.name) + '_' + unicode(self.category_type)

class RatingCategory(models.Model):
    name = models.CharField(max_length = 50)
    description = models.TextField( null = True, blank = True)
    rating_min = models.PositiveIntegerField( default = 0 )
    rating_max = models.PositiveIntegerField( default = 5 )

    def __unicode__(self):
        return self.name        

class EntityRatingCategoryMap(models.Model):
    category = models.ForeignKey(RatingCategory)
    entity_type_id = models.PositiveIntegerField()    

    def __unicode__(self):
        return unicode( self.category ) + '_' + unicode( self.entity_type_id )

    @classmethod
    def get_categories(cls, entity_type ):
        return EntityRatingCategoryMap.objects.filter( entity_type = entity_type )

class RatingVote(models.Model):
    rating_category = models.ForeignKey(EntityRatingCategoryMap)
    content_type = models.ForeignKey( ContentType )    
    object_id = models.PositiveIntegerField()
    rated_object = GenericForeignKey('content_type', 'object_id')
    rating_value = models.PositiveIntegerField()
    rated_by = models.ForeignKey(User)
    rated_on = models.DateTimeField( auto_now_add = True )
    
    @classmethod
    def get_vote_details( cls, entity, entity_map, request ):
        votes = RatingVote.objects.filter( rating_category = entity_map, \
                                        content_type = ContentType.objects.get_for_model(entity), object_id = entity.id )
        return_list = []
        if not ( request.user.is_authenticated and votes.filter( rated_by = request.user.id ).exists() ):
            return_list.append( 0 )
        else:
            return_list.append( 1 )

        avg = 0.0
        total_votes = votes.count()
        if total_votes:        
            for vote in votes:
                avg += vote.rating_value
            avg = (avg/total_votes)
        return return_list + [ total_votes, int(avg) ]

    @classmethod
    def avg_rating(cls, rating_category, content_type, object_id):
        votes = RatingVote.objects.filter( rating_category = rating_category, \
                                        content_type = content_type, object_id = object_id )
        return utils.get_avg_rating( votes )

    @classmethod
    def overall_avg_rating( cls, entity ):
        ratings = RatingVote.objects.filter( content_type = ContentType.objects.get_for_model(entity), object_id = entity.id )
        avg = 0.0
        total_votes = ratings.count()
        if not total_votes:
            return None
        for r in ratings:
            avg += r.rating_value
        avg = (avg/total_votes)        
        return ("%.1f/5"%(avg))

    @classmethod
    def add_vote( cls, entity_map, content_type, object_id, rating_value, user ):
        already_rated = False
        rate = None
        if RatingVote.objects.filter( rating_category = entity_map, content_type = content_type, object_id = object_id, rated_by = user).exists():
            already_rated = True
            rate = RatingVote.objects.filter( rating_category = entity_map, content_type = content_type, object_id = object_id, rated_by = user)[0]
        else:
            rate = RatingVote( rating_category = entity_map, content_type = content_type, object_id = object_id, rated_by = user )
        
        if int( rating_value ) < entity_map.category.rating_min or \
            int( rating_value ) > entity_map.category.rating_max:
            raise Exception('Rating value not correct!')
        rate.rating_value = int( rating_value )
        rate.save()
        return (rate, already_rated )

class Comment( models.Model ):
    text = models.TextField()
    post_date = models.DateTimeField( auto_now_add = True )
    posted_by = models.ForeignKey( User )
    content_type = models.ForeignKey( ContentType )
    object_id = models.PositiveIntegerField()
    comment_object = GenericForeignKey('content_type', 'object_id')
    is_spam = models.BooleanField( default = False )

    @classmethod
    def post_comment(cls, content_type_id, object_id, user, comment ):
        logger.debug('user: %s' %user)
        content_type = ContentType.objects.get( id = content_type_id )
        entity = content_type.get_object_for_this_type( pk = object_id )
        comment = Comment( text = comment, posted_by = user, content_type = content_type, object_id = entity.id )
        comment.save()
        return comment

    @classmethod
    def get_comments( cls, content_type_id, object_id ):
        content_type = ContentType.objects.get( id = content_type_id )
        return Comment.objects.filter( content_type = content_type, object_id = object_id, is_spam = False ).order_by('-post_date')        
        

class Contact(models.Model):
    name = models.CharField( max_length = 100 )
    phone = models.CharField( max_length = 20, null = True, blank = True )
    email = models.EmailField( null = True, blank = True )

    def save(self, *args, **kwargs):
        if self.phone and not self.phone.isdigit():
            raise Exception("phone number is in improper format, please check")
        super( Contact, self ).save( *args, **kwargs )

    def __unicode__(self):
        return unicode(self.name) + '_' + unicode(self.phone)


class Activity(models.Model):
    ACTION_ITEMS = (
            ('VI', 'viewed'),
            ('RA', 'Rated'),
            ('RE', 'Commented'),
            
        )
    user = models.ForeignKey( User, null = True )
    action = models.CharField( max_length = 2, choices = ACTION_ITEMS )
    content_type =  models.ForeignKey( ContentType )
    object_id = models.PositiveIntegerField()
    entity = GenericForeignKey('content_type', 'object_id')
    action_time = models.DateTimeField( default = datetime.now )
    weightage = models.PositiveIntegerField()

    @classmethod
    def note_activity(cls, action, entity, user = None ):
        weightage = Activity_weightage.objects.get( activity_type = action ).weightage
        activity = Activity( action = action, \
        content_type = ContentType.objects.get_for_model(entity), object_id = entity.id, weightage = weightage )
        if user:
            activity.user = user 
        activity.save()
    
    @classmethod    
    def get_latest_activity(cls, min_limit = 0, max_limit = 10 ):

common/forms.py
from django.forms import ModelForm
from models import User_profile
from django.contrib.auth.models import User
from django import forms
from django.core.validators import validate_slug, MinLengthValidator, MaxLengthValidator, RegexValidator
from log import get_request_logger
logger = get_request_logger()
from mall.models import Mall_profile
from gmapi.forms.widgets import GoogleMap

class UserForm(ModelForm): 
    username = forms.CharField(widget=forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Username'}), validators = [ validate_slug, MinLengthValidator(5), MaxLengthValidator(20) ] )
    password = forms.CharField( widget = forms.PasswordInput(attrs = {'class':'form-control', "placeholder": "Enter Password"}), validators = [ validate_slug, MinLengthValidator(7), MaxLengthValidator(30) ] )
    retype_password = forms.CharField( widget = forms.PasswordInput(attrs = {'class':'form-control', "placeholder": "Retype Password"}), validators = [ validate_slug, MinLengthValidator(7), MaxLengthValidator(30) ] )
    email    = forms.EmailField(widget=forms.TextInput(attrs = {'class':'form-control', "placeholder": "Your Email", "type": "email" } ))
    firstname = forms.CharField(widget=forms.TextInput(attrs = {'class':'form-control', "placeholder" : "First Name"}), validators = [ RegexValidator("[a-zA-Z]+", "First Name is invalid.") ] )
    lastname = forms.CharField(widget=forms.TextInput(attrs = {'class':'form-control', "placeholder" : "Last Name"}), validators = [ RegexValidator("[a-zA-Z]+", "Last Name is invalid.") ] )
    role = forms.CharField( widget = forms.HiddenInput() )

    class Meta:
        model = User_profile
        exclude = ( 'user', 'is_verified' )

    def clean(self, *args, **kwargs ):
        super( UserForm, self ).clean(*args, **kwargs)
        
        if User.objects.filter( username = self.cleaned_data.get('username') ).exists():
            raise forms.ValidationError("User %s already exists." %(self.cleaned_data.get('username')))
        
        password = self.cleaned_data.get('password')
        retype =  self.cleaned_data.get('retype_password')
        
        if not ( password and retype ) or ( password != retype ):
            raise forms.ValidationError("Passwords don't match")
        
        return self.cleaned_data


class ProfileForm(ModelForm):    
    class Meta:
        model = User_profile
        fields = ( 'firstname', 'lastname', 'email' )

class MapForm(forms.Form):
    map = forms.Field(widget=GoogleMap(attrs={'width':210, 'height':210}))

templates/common/create_entity_form.html
{% extends 'main.html' %}

{% block content %}
	<div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well well-sm">
          <form class="form-horizontal" action="" method="post">
          {% csrf_token %}
          <fieldset>
            <legend class="text-center">Create {{entity_type }}</legend>
    
            <!-- Name input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="name">Name</label>
              <div class="col-md-9">
                <input id="name" name="name" type="text" placeholder="{{ entity_type }} name" class="form-control">
              </div>
            </div>
            {% ifequal entity_type "store" %}
	    		<div class="form-group">
	              <label class="col-md-3 control-label" for="mall">Mall</label>
	              <div class="col-md-9">
	                <select class="form-control" id="mallist" name="mall">
	                	{% for mall in malls %}
				        <option value="{{ mall.id }}">{{ mall.name }}</option>
				        {% endfor %}
				    </select>
	              </div>
	            </div>
	        {% endifequal %}
            <!-- Email input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="owner">Owner</label>
              <div class="col-md-9">
                <input id="owned_by" name="owned_by" type="text" placeholder="Owner Name" class="form-control">
              </div>
            </div>    
            <!-- Message body -->
            <div class="form-group">
              <label class="col-md-3 control-label" for="description">Description</label>
              <div class="col-md-9">
                <textarea class="form-control" id="description" name="description" placeholder="Please enter the {{ entity_type }} description here..." rows="5"></textarea>
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label" for="phone">Phone</label>
              <div class="col-md-9">
                <input type="text" class="form-control" id="phone" name="phone" placeholder="Contact Phone No."/>
              </div>
              </div>
            <div class="form-group">
              <label class="col-md-3 control-label" for="email">E-Mail</label>
              <div class="col-md-9">
                <input type="text" class="form-control" id="email" name="email" placeholder="Contact Email"/>
              </div>
              </div>
            <div class="form-group">
              <label class="col-md-3 control-label" for="street">Address</label>
              <div class="col-md-9">
                <input type="text" class="form-control" id="street" name="street" placeholder="Location Detail"/>
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label" for="nearby">Nearby</label>
              <div class="col-md-9">
                <input type="text" class="form-control" id="nearby" name="nearby" placeholder="Please add nearby landmark."/>
              </div>
            </div>
            {% ifequal entity_type "mall" %}
            <div class="form-group">
              <label class="col-md-3 control-label" for="lat">Location</label>
              <div class="col-xs-4">
                <input id="latitude" name="latitude" type="text" class="form-control" placeholder="{{ entity_type }} map latitude" />    
              </div>
              <div class="col-xs-4">
                <input id="longitude" name="longitude" type="text" class="form-control" placeholder="{{ entity_type }} map longitude" /> 
              </div>
            </div>
            {% endifequal %}            
            </div>
            <!-- Form actions -->
            <div class="form-group">
              <div class="col-md-12 text-right">
                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
              </div>
            </div>
          </fieldset>
          </form>
        </div>
      </div>
	</div>
{% ifequal entity_type "mall" %}
<style>
      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
      .controls {
        margin-top: 16px;
        border: 1px solid transparent;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        height: 32px;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
      }

      #pac-input {
        background-color: #fff;
        padding: 0 11px 0 13px;
        width: 400px;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        text-overflow: ellipsis;
      }

      #pac-input:focus {
        border-color: #4d90fe;
        margin-left: -1px;
        padding-left: 14px;  /* Regular padding-left + 1. */
        width: 401px;
      }

      .pac-container {
        font-family: Roboto;
      }

      #type-selector {
        color: #fff;
        background-color: #4d90fe;
        padding: 5px 11px 0px 11px;
      }

      #type-selector label {
        font-family: Roboto;
        font-size: 13px;
        font-weight: 300;
      }
}

    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>

    <script>
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(28.6322444, 77.2207238),
    zoom: 13
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
    mapOptions);

  var input = /** @type {HTMLInputElement} */(
      document.getElementById('pac-input'));

  var types = document.getElementById('type-selector');
  map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
  map.controls[google.maps.ControlPosition.TOP_LEFT].push(types);

  var autocomplete = new google.maps.places.Autocomplete(input);
  autocomplete.bindTo('bounds', map);
  autocomplete.setTypes([]);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map,
    anchorPoint: new google.maps.Point(0, -29)
  });

  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
    marker.setIcon(/** @type {google.maps.Icon} */({
      url: place.icon,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(35, 35)
    }));
    marker.setPosition(place.geometry.location);
    marker.setVisible(true);
    document.getElementById('latitude').value = place.geometry.location.lat();
    document.getElementById('longitude').value = place.geometry.location.lng();
    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
  });
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
    <br/>
    <input id="pac-input" class="controls" type="text" placeholder="Enter a location"/>
    <div id="map-canvas"></div>
    
{% endifequal %}

{% endblock %}

templates/common/include_login_block.html
{% load socialaccount %}
 <div class="row">
        <div class="col-md-5">
    <div class="omb_login">
        <div class="row omb_row-sm-offset-3 omb_socialButtons">
            <div class="col-xs-4 col-sm-2">
                <a href="{% provider_login_url "facebook" method="oauth2" %}" class="btn btn-lg btn-block omb_btn-facebook">
                    
                    <span class="hidden-xs"><i class="fa fa-facebook"></i> Facebook</span>
                </a>
            </div>
            <div class="col-xs-4 col-sm-2">
                <a href="{% provider_login_url "twitter" method="oauth2" %}" class="btn btn-lg btn-block omb_btn-twitter">
                    <i class="fa fa-twitter visible-xs"></i>
                    <span class="hidden-xs"><i class="fa fa-twitter"></i> Twitter</span>
                </a>
            </div>  
            <div class="col-xs-4 col-sm-2">
                <a href="{% provider_login_url "google" method="oauth2" %}" class="btn btn-lg btn-block omb_btn-google">
                    
                    <span class="hidden-xs"><i class="fa fa-google-plus"></i> Google+</span>
                </a>
            </div>  
        </div>

        <div class="row omb_row-sm-offset-3 omb_loginOr">
            <div class="col-xs-12 col-sm-6">
                <hr class="omb_hrOr">
                <span class="omb_spanOr">or</span>
            </div>
        <div class="col-xs-2 col-md-offset-5">
            <h3><a href="{% url 'signup' %}?role=ru">Sign up</a></h3>
        </div>

        </div>             
    </div>

templates/common/main_home.html
{% extends 'main.html' %}

{% block content %}
<br/>
<form class="navbar-form" id="searchForm" method="get" action="/search">
  <div class="input-group input-group-lg col-xs-offset-2 col-xs-6">
  <input type="text" id="id_q" name="q" class="form-control typeahead" placeholder="Search Malls or Shops here..."/>
</div>
<span class="input-group input-group-btn">
	<button type="submit" class="btn btn-primary btn-group-lg">Search</button>
</span>
</form>
<br/>
{% load socialaccount %}
 <div class="row">
        <div class="col-md-10">
    <div class="omb_login">
        <div class="row omb_row-sm-offset-3 omb_socialButtons">
            <div class="col-xs-4 col-sm-2">
                <a href="{% provider_login_url "facebook" method="oauth2" %}" class="btn btn-lg btn-block omb_btn-facebook">
                    
                    <span class="hidden-xs"><i class="fa fa-facebook"></i> Facebook</span>
                </a>
            </div>
            <div class="col-xs-4 col-sm-2">
                <a href="{% provider_login_url "twitter" method="oauth2" %}" class="btn btn-lg btn-block omb_btn-twitter">
                    <i class="fa fa-twitter visible-xs"></i>
                    <span class="hidden-xs"><i class="fa fa-twitter"></i> Twitter</span>
                </a>
            </div>  
            <div class="col-xs-4 col-sm-2">
                <a href="{% provider_login_url "google" method="oauth2" %}" class="btn btn-lg btn-block omb_btn-google">
                    
                    <span class="hidden-xs"><i class="fa fa-google-plus"></i> Google+</span>
                </a>
            </div>  
        </div>

        <div class="row omb_row-sm-offset-3 omb_loginOr">
            <div class="col-xs-12 col-sm-6">
                <hr class="omb_hrOr">
                <span class="omb_spanOr">or</span>
            </div>
        <div class="col-xs-2 col-md-offset-5">
            <h3><a href="{% url 'signup' %}?role=ru">Sign up</a></h3>
        </div>

        </div>             
    </div>
    </div>
    </div>
<br/>
<div class="row">
	<div class="col-xs-5 col-xs-offset-4">
	<script>
    jQuery(document).ready(function($) {

        // Select your slider element and call Flow Slider plugin.
        var $slider = $("#slider");
        $slider.FlowSlider({

            controllerOptions: [{
                mouseStart:100,
                mouseEnd:100,
            }],

            marginStart:20,
            marginEnd:20,
            mode:"horizontal"    
        });    
    });
</script>
<br/>
<br/>
	<div id="slider">
        <div class="row">
        {% load helpers %}
        {% for activity in activities %}
        <div class="col-xs-4">
        <div class="col-xs-3">
        {% with activity|get_activity_entity as aentity %}
            <p>{{ activity.user.username }}</p>
            <p>{{ activity.get_action_display }}</p>
            <p>{{ aentity }}</p>
            
        {% endwith %}
        </div> 
        </div>        
        {% endfor %}
        </div>
    </div>
	</div>
    </div>


{% endblock %}

templates/common/mall_detail.html
{% extends 'common/generic_detail.html' %}

{% block name %}
 {{entity.name }}
{% endblock %}

{% block menu %}
<ul class="nav nav-tabs">
  <li role="presentation" {% ifequal selected 'home' %} class="active" {% endifequal %}><a href="{{ entity.get_absolute_url }}">Home</a></li>
  <li role="presentation" {% ifequal selected 'presentation' %} class="active" {% endifequal %}><a href="#">Profile</a></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>
{% ifequal entity.get_type 'ST' %}

{% endifequal %}
{% endblock %}

templates/common/store_detail.html
{% extends 'common/generic_detail.html' %}

{% block name %}
 {{store.name }}
{% endblock %}

{% block menu %}
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  <li role="presentation"><a href="#">Detail</a></li>
</ul>
{% endblock %}